# Default values for issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

baseDomain: qiot-project.io
wildcardDomain: "apps.qiot-datacenter-4.blueprints.rhecoeng.com"

issuer:
  vault:
    namespace: hashicorp
    secret: vault-vault-bootstrap
    server: https://vault-internal.hashicorp.svc.cluster.local:8200
    image:
      repository: "hashicorp/vault"
      tag: "1.11.2"
